exclude-labels:
  - skip changelog
  - release

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

autolabeler:
  - label: breaking
    title:
      # Example: feat!: ...
      - '/^(build|chore|ci|depr|docs|feat|fix|perf|refactor|release|test)(\(.*\))?\!\: /'
  - label: build
    title:
      - '/^build/'
  - label: internal
    title:
      - '/^(chore|ci|refactor|test)/'
  - label: deprecation
    title:
      - '/^depr/'
  - label: documentation
    title:
      - '/^docs/'
  - label: enhancement
    title:
      - '/^feat/'
  - label: fix
    title:
      - '/^fix/'
  - label: performance
    title:
      - '/^perf/'
  - label: release
    title:
      - '/^release/'

template: |
  $CHANGES

  Thank you to all our contributors for making this release possible!
  $CONTRIBUTORS